### ISSUE TITLE
`pprint-kotlin-core` publication seems broken

### ISSUE THREAD

**Issue by Kantis** [deusaquilus/pprint-kotlin#8]
Following the setup guide and adding 
```kotlin
dependencies {
   implementation("io.exoquery:pprint-kotlin:2.0.0")
}
```

results in broken classpath

<img width="1007" alt="image" src="https://github.com/deusaquilus/pprint-kotlin/assets/316857/1fd4c7fa-05ba-411d-99fe-76f8cf2a25e5">

---

I believe this is caused by `pprint-kotlin-core` being a KMP module, which only publishes variant metadata in the "root module" `pprint-kotlin-core`. Consumers are supposed to be variant-aware, but I'm guessing something goes wrong due to `pprint-kotlin` being a JVM-only module which perhaps doesn't pull along the correct dependency.

For instance, if you look at my dependency graph you can see that other multiplatform dependencies pull along their jvm variants
<img width="440" alt="image" src="https://github.com/deusaquilus/pprint-kotlin/assets/316857/237510e4-b4af-4bb9-b99f-dd90f937b123">

**Comment by Kantis** [comment]
Seems to be broken when trying to use `io.exoquery:pprint-kotlin-kmp` as well

**Comment by deusaquilus** [comment]
Should be fixed in `v2.0.2`. Could you please try it out?

**Comment by Kantis** [comment]
Both the KMP and JVM artifacts seem fine now. Thanks!

**Comment by raamcosta** [comment]
I still cannot import pprint function from jvm module correctly with 2.0.2.

Adding the dependency to `io.exoquery:pprint-kotlin:2.0.2` doesn't seem to do anything for me, I still can't import `io.exoquery` package.

If I change version to 1.1.0 or use `-kmp` dependency, it works, but with kmp version I have to use kotlinx serialization which I don't want to do. Since it's a JVM only module, I'd rather just use reflection.

**Comment by deusaquilus** [comment]
@raamcosta It looks like you need to have `jvmToolchain(11)` for this to work. I'm not sure why.
Sorry I didn't see this. I moved the repo to http://github.com/exoquery/pprint-kotlin.

---
![image](https://github.com/user-attachments/assets/048d5808-6164-4490-beca-ed56f2e15177)

---
![image](https://github.com/user-attachments/assets/23b5b6dd-dc53-4b8a-b984-6f2d802120f8)
